RRTT | a README.md file with a Group description.
notero-edtech/BUxNoteroChallenge pull request #10
Opened 2023-10-17 07:10 UTC by kenzera23

a README.md file with a Group description (Team Name, Description, Members, etc.)

2023-10-18 01:22 UTC, TongKajornpop approved these changes
LGTM

2023-10-18 01:32 UTC, KirimaK approved these changes
LGTM

2023-10-22 17:17 UTC, nathakorn-bnkmutech commented
@KirimaK @TongKajornpop 

ผมเห็นไฟล์มีถูกแก้ไขทั้งหมด 9 ไฟล์
พวกเราแช็คกันหมดแล้วใช่มะ

2023-10-22 17:21 UTC, kenzera23 commented
@nathakorn-bnkmutech อันนี้น่าจะ Push ผิดครับพี่ป๊อบ ขออภัยด้วยครับ

2023-10-22 17:25 UTC, nathakorn-bnkmutech commented
@kenzera23 
ผมขอ reject ไปก่อนนะครับ จนกว่าจะ push ขึ้นมาถูกครับ

2023-10-22 17:25 UTC, kenzera23 commented
> @kenzera23 ผมขอ reject ไปก่อนนะครับ จนกว่าจะ push ขึ้นมาถูกครับ

รับทราบครับ ขอบคุณมากครับ

2023-10-22 17:26 UTC, nathakorn-bnkmutech requested changes
รอ นศ แก้ไฟล์

2023-10-27 01:27 UTC, KirimaK approved these changes
LGTM

2023-10-27 01:33 UTC, TongKajornpop approved these changes
LGTM

2023-10-27 01:35 UTC, thawatchai6442 approved these changes
LGTM

2023-10-27 01:39 UTC, merged