Octopuz README.md
notero-edtech/BUxNoteroChallenge pull request #12
Opened 2023-10-22 01:50 UTC by veerachai12

Training

2023-10-22 17:29 UTC, nathakorn-bnkmutech requested changes

2023-10-22 17:29 UTC, nathakorn-bnkmutech commented on README.md
> +Test description
@veerachai12 ฝากลบไฟล์นี้ทิ้งด้วยครับ

2023-10-23 03:17 UTC, TongKajornpop commented on Assets/BU/Octopuz/README.md.
> +- **ตรัยรักษ์ ชำนาญ Name**: Game Developer
Typo `**ตรัยรักษ์ ชำนาญ Name**` ลืมลบ Name

2023-10-23 03:17 UTC, TongKajornpop commented on Assets/BU/Octopuz/README.md.
> +- (https://drive.google.com/drive/folders/10vMI50B0dHymk4-HEJPH4kMY_S9bnF2g?usp=share_link)
อันนี้ใส่ชื่อ ref ใน [ ] หน่อยคับ

2023-10-24 10:31 UTC, closed without merging