Gameplay version1 Mascot
notero-edtech/BUxNoteroChallenge pull request #17
Opened 2023-11-01 06:35 UTC by OattTitipan

Mascot ที่ขึ้นทุกๆ15% โดยตัวแรก(Wolfgang) จะขึ้นมาตั้งแต่ Start game 
-> 15% ตัวที่2(MasterRo) 
-> 30% ตัวที่3(RothMarley) 
-> 45% ตัวที่4(Rocky) 
-> 60% ตัวที่5(Poppy) 
-> 75% ตัวที่6(Kevin)

2023-11-02 02:38 UTC, nathakorn-bnkmutech requested changes

2023-11-02 02:38 UTC, nathakorn-bnkmutech commented on ProjectSettings/RiderScriptEditorPersistedState.asset
เดี๋ยวพี่ๆ ignore file นี้ให้นะครับ
@KirimaK @thawatchai6442 @TongKajornpop

2023-11-02 02:38 UTC, nathakorn-bnkmutech commented on Assets/Plugins/Easy Save 3/Resources/ES3/ES3Defaults.asset
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:38 UTC, nathakorn-bnkmutech commented on Assets/Resources/Settings/MIDISettings.asset
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:38 UTC, nathakorn-bnkmutech commented on Assets/Resources/soundfont.sf2.bytes.meta
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:38 UTC, nathakorn-bnkmutech commented on ProjectSettings/GvhProjectSettings.xml
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:38 UTC, nathakorn-bnkmutech commented on .idea/.idea.Notero/.idea/.gitignore
![image](https://github.com/notero-edtech/BUxNoteroChallenge/assets/95496322/8af5995c-b67d-4bab-a26c-1f1db40b9374)

ถ้าไม่ได้ตั้งใจแก้ไฟล์พวกนี้ ไม่ต้อง commit ขึ้นมานะครับ

2023-11-02 08:02 UTC, OattTitipan commented on .idea/.idea.Notero/.idea/.gitignore
เเล้วถ้าที่ผมก็อป Example ไปวางใน folder กลุ่มของผมและมันมีไฟล์นี้อยู่ด้วยตามที่ก็อปมา ก็ยังต้อง Commit ใช่มั้ยครับ

2023-11-02 08:11 UTC, TongKajornpop commented on .idea/.idea.Notero/.idea/.gitignore
มันมีไฟล์นี้ติดมาด้วยตอน copy งี้หรอครับ

2023-11-02 08:40 UTC, OattTitipan commented on .idea/.idea.Notero/.idea/.gitignore
ผมดูผิดคิดว่าเป็นตัวเดียวกันครับ ขอโทษครับ
และก็ผมก็อป MidiGamplayExample เเละก็ย้าย Sprites กับ Prefabs ที่ทำ Mascot  ไปใส่ folderกลุ่ม(Chainpunch)เรียบร้อยครับ
ต่อมาก็เปลี่ยน namespace เสร็จ ดูไฟล์ที่จะ Commit ก็เห็นไฟล์ในรูป
![image](https://github.com/notero-edtech/BUxNoteroChallenge/assets/148039432/59427ca2-040a-4e74-a710-da64f1c6b2c7)

ไฟล์ในรูปก็มาจากการก็อป MidiGameplayExample ครับ อย่างงี้ก็ต้อง Commit ใช่มั้ยครับ

2023-11-02 09:34 UTC, TongKajornpop commented on .idea/.idea.Notero/.idea/.gitignore
รู้สึกว่า .idea folder จะมาจาก JetBrains Rider รึเปล่า น้องใช้ Rider ใช่มััยครับ?

2023-11-02 10:03 UTC, OattTitipan commented on .idea/.idea.Notero/.idea/.gitignore
ใช่ครับผมใช้ Rider

2023-11-02 10:12 UTC, TongKajornpop commented on .idea/.idea.Notero/.idea/.gitignore
เดี๋ยวขอปรึกษาทีมแปบคับ พน.น่าจะให้คำตอบได้

2023-11-03 06:26 UTC, TongKajornpop commented on .idea/.idea.Notero/.idea/.gitignore
เบื้องต้นน้องลองลบไฟล์สามตัวนี้แล้วลองเปิด Rider กับ Unity ทำงานว่าปกติมั้ย แล้วไฟล์มัน regen กลับมามั้ยหน่อยครับ

2023-11-03 07:29 UTC, OattTitipan commented on .idea/.idea.Notero/.idea/.gitignore
ผมลองลบไฟล์ดูเเล้วครับ เป็นปกติดี ไฟล์ไม่ regen กลับมาครับ

2023-11-03 07:32 UTC, TongKajornpop commented on .idea/.idea.Notero/.idea/.gitignore
งั้นก็ตามนี้เลยครับ

2023-11-03 07:34 UTC, OattTitipan commented on .idea/.idea.Notero/.idea/.gitignore
งั้นผมลบทั้ง folder .ideaเลยนะครับ และต้อง commit ด้วยมั้ยครับว่าลบไฟล์พวกนี้

2023-11-03 07:51 UTC, TongKajornpop commented on .idea/.idea.Notero/.idea/.gitignore
commit ครับ

2023-11-10 02:59 UTC, TongKajornpop commented on Assets/AssetData/Animations/VFXTexts/vfx_oops_old.anim
อันนี้เอาเข้าไป folder กลุ่มตัวเองนะครับ

2023-11-12 10:56 UTC, OattTitipan commented on Assets/AssetData/Animations/VFXTexts/vfx_oops_old.anim
ผมก็อปของที่มีอยู่เเล้ว มาทำใหม่ใน Folder กลุ่มตัวเองเรียบร้อยเเล้วครับ

2023-11-13 09:21 UTC, TongKajornpop commented
อันนี้น้องไม่ได้ PR จาก dev branch ของฝั่งน้องนี่ครับ
งานที่แยกไปทำใน sub branch พอเสร็จและพร้อมจะ PR ให้เอาเข้า Dev ของตัวเองก่อนนะครับ (test ใน dev ของน้องก่อน) แล้วค่อยเปิด PR จาก dev น้องมา dev พี่ นะครับ

2023-11-14 07:24 UTC, closed without merging