Update ReadME.md
notero-edtech/BUxNoteroChallenge pull request #18
Opened 2023-11-01 11:29 UTC by Kornthawat

2023-11-02 02:00 UTC, TongKajornpop commented on README.md
> +# **TOMATO**: TOMATO
```suggestion
# **Team Name**: TOMATO
```

2023-11-02 02:27 UTC, nathakorn-bnkmutech requested changes

2023-11-02 02:27 UTC, nathakorn-bnkmutech commented on Assets/AssetData/Animations/ui_guide_cursor_controller.controller
ถ้าไม่ได้ตั้งใจเปลี่ยนไฟล์นี้ ไม่ต้อง commit ขึ้นมานะครับ

2023-11-02 02:30 UTC, TongKajornpop commented on README.md
ย้ายไป folder ที่บอกตามในการบ้านนะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech requested changes

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on Assets/AssetData/Sprites/UI/Technical/MaskAlpha-Rectangle-C16.png.meta
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on Assets/AssetData/Sprites/UI/Technical/MaskAlpha-Rectangle-C8.png.meta
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on Assets/PlayMaker/Editor/Resources/EditorStartupPrefs.asset
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on Assets/Plugins/Easy Save 3/Resources/ES3/ES3Defaults.asset
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on Assets/Resources/Settings/MIDISettings.asset
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on Assets/Resources/soundfont.sf2.bytes.meta
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 02:31 UTC, nathakorn-bnkmutech commented on ProjectSettings/Packages/com.unity.services.core/Settings.json
ไม่ต้อง commit file ที่ไม่ได้ตั้งใจ change ขึ้นมานะครับ

2023-11-02 03:55 UTC, TongKajornpop commented on Assets/Notero/RaindropGameplay/UI/ComboPanel.cs
อันนี้ย้ายไป folder กลุ่มตัวเอง

2023-11-02 04:01 UTC, TongKajornpop commented on Assets/Notero/RaindropGameplay/UI/CompetitivePanel.cs
ไฟล์นี้ไม่ให้แก้นะคับ เรื่องเพิ่ม combo panel นี่ แนะนำเป็นไปเพิ่มที่ GameUIConnector ได้เลย (อันที่น้องก็อปมาแล้วเปลี่ยน namespace แล้วนะ) ถ้างง นัดถามได้เลยคับ

2023-11-13 01:28 UTC, closed without merging

2023-11-13 01:29 UTC, TongKajornpop commented
Deplicated.
Already mearg read me in separate PR.