NineTails | Gameplay & Visual Update
notero-edtech/BUxNoteroChallenge pull request #20
Opened 2023-11-03 06:08 UTC by BelfeZ

2023-11-03 07:34 UTC, TongKajornpop commented on Assets/sand_castle1.png
อันนี้ต้องย้ายไปไว้ใน folder กลุ่มตัวเองนะครับ

2023-11-03 07:35 UTC, TongKajornpop commented on Assets/PlayMaker/Editor/Resources/EditorStartupPrefs.asset
อันนี้ไม่ต้อง commit ครับ

2023-11-03 07:35 UTC, TongKajornpop commented on Assets/Plugins/Easy Save 3/Resources/ES3/ES3Defaults.asset
อันนี้ไม่ต้อง commit ครับ

2023-11-03 07:37 UTC, thawatchai6442 requested changes
folder `MidiGameplayExxample` ไม่อนุญาติแก้ไขน่ะครับ
ให้ coppy folder `MidiGameplayExxample` แล้วไปเปลี่ยนเป็นของตัวเองแทนครับ

2023-11-03 07:37 UTC, thawatchai6442 commented on ProjectSettings/GvhProjectSettings.xml
file นี้ไม่ต้อง commit ครับ

2023-11-03 07:37 UTC, thawatchai6442 commented on Assets/sand_castle1.png
เพิ่มไฟผิด folder ป่าวน่ะ?

2023-11-03 07:37 UTC, thawatchai6442 commented on Assets/sand_castle1.png.meta
เพิ่มไฟผิด folder ป่าวน่ะ?

2023-11-03 11:28 UTC, BelfeZ commented on Assets/sand_castle1.png
เพิ่มผิดครับ เดียวผมปรับแก้ส่วนอื่นๆก่อนเดียวส่ง PR ไปอีกรอบนะครับ

2023-11-03 11:29 UTC, BelfeZ commented on Assets/sand_castle1.png.meta
เพิ่มผิดครับๆ

2023-11-03 11:30 UTC, BelfeZ commented on Assets/sand_castle1.png
เดียวผมลบออกและ PR ไปใหม่ครับผม

2023-11-03 13:01 UTC, BelfeZ commented
ผม PR ใหม่แล้วนะครับ

2023-11-06 11:06 UTC, TongKajornpop commented on .gitignore
ไฟล์ ignore หลักตัวนี้ห้ามแก้นะครับ (เดี๋ยวจะมีที่พี่ๆ แก้จากฝั่งพี่เพิ่มให้เอง)

2023-11-06 11:11 UTC, TongKajornpop commented on Assets/BU/Chainpunch.meta
.meta ที่ไม่เกี่ยวกับของกลุ่มน้องไม่ต้องเอาเข้านะครับ

2023-11-06 11:12 UTC, TongKajornpop commented on Assets/BU/Chainpunch/README.md.meta
.meta ที่ไม่เกี่ยวกับของกลุ่มน้องไม่ต้องเอาเข้านะครับ

2023-11-06 15:58 UTC, BelfeZ commented on .gitignore
ครับผม ให้ผมแก้กลับไหมครับ

2023-11-08 02:50 UTC, TongKajornpop commented on .gitignore
แก้กลับครับ

2023-11-09 08:42 UTC, TongKajornpop commented on .gitignore
> +.DS_Store
```suggestion
```

2023-11-13 01:54 UTC, TongKajornpop commented on Assets/BU/NineTails/BU.MidiGameplay.asmdef
เปลี่ยนชื่อไฟล์หน่อยนะครับ กันสับสนกับของเดิม เอาให้ตรงกับ names]ace ก็ได้

2023-11-13 06:46 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/Gameplay/BaseRaindrop.cs
class นี้น้องดัดแปลงมาจาก Base Raindrop Note Controller ทำมาเพื่อเป็น parent ใหม่ให้ Demo Raindrop Note Controller
แต่จริงๆ น้องสามารถแก้ virtual method จากใน Demo Raindrop Note Controller ที่ inherit จาก Base Raindrop Note Controller ได้เลยนะครับ ลองศึกษา keyword: virtual method ดู

2023-11-13 06:52 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/Gameplay/CharactersAnimationController.cs
> +        private bool ownNote;
ตาม https://drive.google.com/drive/folders/1Q-QacNbPCZ7LJaVFszfs-mj20IxLzJzi?usp=drive_link
private naming เป็น m_PascalCase

2023-11-13 06:59 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/IGameplayUIControllable.cs
อันนี้ลบได้ครับ patch ใหม่ได้ย้าย interface นี้เข้า Notero library ให้แล้ว

2023-11-13 07:00 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/HealthSliderController.cs
> +        private bool isDead;
check naming convention

2023-11-13 07:02 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/HealthSliderController.cs
> +            if  (isDead == false)
`if` ตรงนี้ไม่จำเป็นแล้วรึเปล่า เพราะ set `isDead = false` แล้ว

2023-11-13 07:20 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/HealthSliderController.cs
> +            if (isDead == false)
ใช้ inverse if ได้
`if(isDead) return;`

2023-11-13 07:34 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/HealthSliderController.cs
> +            }
Optional Refactor เกี่ยวกับของใน Update:
Level 1 : Extract method
Level 2 : เขียนให้ไม่ต้องพึ่ง Update
เสนอเฉยๆ ไม่ต้องทำก็ได้

2023-11-13 07:35 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/GameplayUIConnector.cs
> +        }*/
ถ้าไม่ใช้ก็ลบออกเลยคับ

2023-11-13 07:36 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/GameplayUIConnector.cs
> +            //m_VirtualPiano.SetActive(isActive);
ถ้าไม่ใช้ก็ลบออกเลยคับ

2023-11-13 07:36 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/GameplayUIConnector.cs
> +            //m_OctaceBar.SetActive(isActive);
ถ้าไม่ใช้ก็ลบออกเลยคับ

2023-11-13 07:36 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/GameplayUIConnector.cs
> +        private GameObject m_Barline;*/
ถ้าไม่ใช้ก็ลบออกเลยคับ

2023-11-13 07:38 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/GameplayUIConnector.cs
> +        private GameObject m_HealthBar;*/
ถ้าไม่ใช้ก็ลบออกเลยคับ

2023-11-15 08:10 UTC, TongKajornpop commented on Assets/PlayMaker/Editor/Resources/EditorStartupPrefs.asset
ไฟล์นี้ต้อง revert อีกรอบ

อันนี้น่าจะเคย revert แล้วรึเปล่า
ตอน stage เลือกเฉพาะไฟล์ที่เราตั้งใจแก้ไขเท่านั้นนะครับ

2023-11-15 08:10 UTC, TongKajornpop commented on Assets/Plugins/Easy Save 3/Resources/ES3/ES3Defaults.asset
ไฟล์นี้ต้อง revert อีกรอบ

อันนี้น่าจะเคย revert แล้วรึเปล่า
ตอน stage เลือกเฉพาะไฟล์ที่เราตั้งใจแก้ไขเท่านั้นนะครับ

2023-11-15 18:20 UTC, BelfeZ commented on Assets/Plugins/Easy Save 3/Resources/ES3/ES3Defaults.asset
ทีมน่าจะพลาดฮะ เดียวผมแก้ให้ครับ

2023-11-16 08:38 UTC, BelfeZ commented on Assets/Plugins/Easy Save 3/Resources/ES3/ES3Defaults.asset
แก้แล้วครับ

2023-11-16 09:37 UTC, TongKajornpop commented on Assets/BU/NineTails/Scripts/UI/IGameplayUIControllable.cs
ไฟล์นี้ หลังจาก patch แล้ว มันย้ายไปอยู่ใน `Notero.RaindropGameplay.UI` แล้ว
น้องลบไฟล์นี้ออกได้เลย
อย่าลืมลองให้ Unity compile สักรอบ ดูว่า ref มันหลุดรึเปล่า

2023-11-16 09:50 UTC, TongKajornpop approved these changes
LGTM

2023-11-16 10:03 UTC, TongKajornpop commented
รอ resolve ไฟล์ `Assets/BU/NineTails/Scripts/UI/IGameplayUIControllable.cs`

2023-11-22 06:08 UTC, TongKajornpop approved these changes
LGTM

2023-11-22 06:41 UTC, thawatchai6442 approved these changes
LGTM

2023-11-22 07:08 UTC, TongKajornpop approved these changes
LGTM

2023-11-22 07:09 UTC, merged