RRTT | Boss Anim (Instructor : CountDown, Question & Student : Result), fixed charts (V1.0)
notero-edtech/BUxNoteroChallenge pull request #44
Opened 2023-11-30 18:47 UTC by kenzera23

2023-12-04 11:26 UTC, KirimaK requested changes

2023-12-04 11:26 UTC, KirimaK commented on Assets/Notero/Unity/UI/Quiz/ChartUI.cs
ไฟล์นี้น้องห้ามแก้นะคะ

2023-12-04 12:08 UTC, kenzera23 commented on Assets/Notero/Unity/UI/Quiz/ChartUI.cs
@KirimaK เหมือนพี่เกมบอกให้แก้ Chart ไปครับ หรือต้อง copy มาใน folder ตัวเองละลิงก์ใหม่ครับ

2023-12-04 12:24 UTC, kenzera23 commented
@KirimaK แก้ไฟล์ og ให้เป็นปกติแล้วนะครับ พร้อมกับ copy .cs มาไว้ใน Project ตัวเองแล้วครับผม

2023-12-06 01:11 UTC, KirimaK approved these changes
LGTM

2023-12-06 03:49 UTC, merged